drop table if exists member CASCADE;
create table member
(
    -- generated by default as identity : null 값이 세팅되면 db가 자동으로 id 값 부여
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);